### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by JDdeArco** [jesuswebdev/react-auction-api#1]
Hey man, I was assigned a project in class, building an auction page in React. Just like your project. But I don't know how to run this repository. your help would be extraordinary.

**Comment by jesuswebdev** [comment]
Hello, sorry for the late reply. This is an unfinished project and it is poorly written in some parts.

I cloned it and got it to work by replacing the MongoDB URI in the `config/env/*.js` files. Again, this is poorly written and not the way you want to manage your config variables.

After replacing the MongoDB URI you should be able to start it by running `npm start` or test with `npm test`
